```{r echo = F}

# Strings to match samples and create labels
#gene <- "{{.x}}"
sample <- "{{sample}}"
sect_title <- sample

if(!exists("extra_pound_gene_all")){
  extra_pound_gene_all <- ""
}

sample_info <- sample_list[[sample]]

```

###`r extra_pound_gene_all` **`r sect_title`** {.tabset}

```{r {{sample}}-all_gene, fig.height=8, fig.width=8}
merged_seurat <- sample_info$seurat_object
cluster_colors <- sample_info$cluster_colors

sep_1 <- violin_col_by_1 <- "cluster_celltype"
colors_1 <- cluster_colors
umap_cols_1 <- colors_1

if(sample_info$type == "combined"){
  sep_2 <- violin_col_by_2 <- "RNA_combined_celltype"
} else {
  sep_2 <- violin_col_by_2 <- "RNA_celltype"
}
colors_2 <- umap_cols_2 <- celltype_colors

plot_type = "rna.umap"

assay <- "RNA"

gene_template <- file.path(here(), "src/scripts/templates/gene_plot_template.Rmd")

extra_pound_gene <- paste0(extra_pound_gene_all, "#")

gene_chunks <- genes %>%
  map(~knit_expand(file = gene_template, sample = sample, group = "group1",
                   gene = .x, subset = FALSE))
```

`r knit_child(text = gene_chunks)`