library(tidyverse)
library(here)
library(pheatmap)
library(viridis)
library(pathview)
library(openxlsx)
library(gprofiler2)
library(knitr)
library(markdown)
library(LaCroixColoR) # johannesbjork/LaCroixColoR
library(rmarkdown)
library(MetBrewer) # BlakeRMills/MetBrewer
library(inauguration) # ciannabp/inauguration
library(ATACseqQC)
library(Rsamtools)
# library(TxDb.Mmusculus.UCSC.mm10.knownGene)
# library(BSgenome.Mmusculus.UCSC.mm10)
# library(BSgenome.Hsapiens.UCSC.hg38)
# library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(ChIPpeakAnno)
library(DiffBind)
library(GenomicRanges)
library(ChIPseeker)