library(tidyverse)
library(here)
library(pheatmap)
library(viridis)
library(pathview)
library(openxlsx)
library(gprofiler2)
library(knitr)
library(markdown)
library(LaCroixColoR) # johannesbjork/LaCroixColoR
library(rmarkdown)
library(MetBrewer) # BlakeRMills/MetBrewer
library(inauguration) # ciannabp/inauguration
library(DESeq2)
library(ggrepel)
library(cowplot)
library(Matrix)
library(RColorBrewer)
library(ashr)
library(apeglm)
library(KEGGREST)
library(org.Mm.eg.db)